namespace LinqActivity
{
    public class Seeder
    {
        public static List<Aluno> GetAlunos()
        {
            return new List<Aluno>
            {
                new Aluno { Codigo = "A00001", Nome = "Isabella Santos", DataNascimento = new DateTime(1997, 7, 7), Email = "isabella.santos@email.com" },
                new Aluno { Codigo = "A00002", Nome = "Carlos Ribeiro", DataNascimento = new DateTime(2005, 6, 17), Email = "carlos.ribeiro@gmail.com.br" },
                new Aluno { Codigo = "A00003", Nome = "Diego Fernandes", DataNascimento = new DateTime(1963, 5, 16), Email = "diego.fernandes@email.com" },
                new Aluno { Codigo = "A00004", Nome = "Ana Silva", DataNascimento = new DateTime(1959, 7, 28), Email = "ana.silva@gmail.com" },
                new Aluno { Codigo = "A00005", Nome = "Laura Oliveira", DataNascimento = new DateTime(1999, 10, 23), Email = "laura.oliveira@email.com" },
                new Aluno { Codigo = "A00006", Nome = "Manuela Ribeiro", DataNascimento = new DateTime(1991, 4, 14), Email = "manuela.ribeiro@email.com" },
                new Aluno { Codigo = "A00007", Nome = "João Carvalho", DataNascimento = new DateTime(1954, 7, 4), Email = "joão.carvalho@email.com" },
                new Aluno { Codigo = "A00008", Nome = "Ana Rodrigues", DataNascimento = new DateTime(1983, 6, 23), Email = "ana.rodrigues@gmail.com" },
                new Aluno { Codigo = "A00009", Nome = "Gabriel Rodrigues", DataNascimento = new DateTime(1958, 10, 11), Email = "gabriel.rodrigues@gmail.com@" },
                new Aluno { Codigo = "A00010", Nome = "Julia Rodrigues", DataNascimento = new DateTime(1963, 1, 12), Email = "julia.rodrigues@email.com" },
                new Aluno { Codigo = "A00011", Nome = "João Oliveira", DataNascimento = new DateTime(1992, 9, 19), Email = "joão.oliveira@email.com" },
                new Aluno { Codigo = "A00012", Nome = "Carlos Rodrigues", DataNascimento = new DateTime(2009, 11, 10), Email = "carlos.rodrigues@email.com" },
                new Aluno { Codigo = "A00013", Nome = "Isabella Oliveira", DataNascimento = new DateTime(1986, 1, 16), Email = "isabella.oliveira@email.com" },
                new Aluno { Codigo = "A00014", Nome = "Isabella Souza", DataNascimento = new DateTime(1990, 4, 10), Email = "isabella.souza@email.com" },
                new Aluno { Codigo = "A00015", Nome = "Manuela Fernandes", DataNascimento = new DateTime(1992, 10, 12), Email = "manuela.fernandes@email.com" },
                new Aluno { Codigo = "A00016", Nome = "Carlos Silva", DataNascimento = new DateTime(1952, 6, 2), Email = "carlos.silva@email.com" },
                new Aluno { Codigo = "A00017", Nome = "Beatriz Gomes", DataNascimento = new DateTime(1987, 12, 14), Email = "beatriz.gomes@email.com" },
                new Aluno { Codigo = "A00018", Nome = "Diego Alves", DataNascimento = new DateTime(1972, 12, 28), Email = "diego.alves@email.com" },
                new Aluno { Codigo = "A00019", Nome = "Diego Rodrigues", DataNascimento = new DateTime(1993, 2, 10), Email = "diego.rodrigues@email.com" },
                new Aluno { Codigo = "A00020", Nome = "Isabella Lima", DataNascimento = new DateTime(1957, 4, 30), Email = "isabella.lima@email.com" },
                new Aluno { Codigo = "A00021", Nome = "Sofia Gomes", DataNascimento = new DateTime(2007, 9, 15), Email = "sofia.gomes@email.com" },
                new Aluno { Codigo = "A00022", Nome = "Beatriz Souza", DataNascimento = new DateTime(2006, 5, 13), Email = "beatriz.souza@email.com" },
                new Aluno { Codigo = "A00023", Nome = "Carlos Costa", DataNascimento = new DateTime(1981, 10, 24), Email = "carlos.costa@email.com.br" },
                new Aluno { Codigo = "A00024", Nome = "Alice Fernandes", DataNascimento = new DateTime(1989, 8, 18), Email = "alice.fernandes@email.com" },
                new Aluno { Codigo = "A00025", Nome = "Laura Silva", DataNascimento = new DateTime(1995, 5, 13), Email = "laura.silva@email.com" },
                new Aluno { Codigo = "A00026", Nome = "Rafael Araujo", DataNascimento = new DateTime(1985, 6, 29), Email = "rafael.araujo@email.com" },
                new Aluno { Codigo = "A00027", Nome = "Beatriz Alves", DataNascimento = new DateTime(1994, 6, 25), Email = "beatriz.alves@email.com" },
                new Aluno { Codigo = "A00028", Nome = "Valentina Lima", DataNascimento = new DateTime(2002, 6, 26), Email = "valentina.lima@email.com" },
                new Aluno { Codigo = "A00029", Nome = "Gabriel Monteiro", DataNascimento = new DateTime(1951, 7, 20), Email = "gabriel.monteiro@email.com" },
                new Aluno { Codigo = "A00030", Nome = "Felipe Araujo", DataNascimento = new DateTime(2005, 5, 18), Email = "felipe.araujo@email.com" },
                new Aluno { Codigo = "A00031", Nome = "Manuela Mendes", DataNascimento = new DateTime(1980, 9, 15), Email = "manuela.mendes@email.com" },
                new Aluno { Codigo = "A00032", Nome = "Carlos Ribeiro", DataNascimento = new DateTime(1983, 5, 27), Email = "carlos.ribeiro@email.com" },
                new Aluno { Codigo = "A00033", Nome = "Gustavo Ribeiro", DataNascimento = new DateTime(1980, 5, 27), Email = "gustavo.ribeiro@email.com" },
                new Aluno { Codigo = "A00034", Nome = "Isabella Fernandes", DataNascimento = new DateTime(1953, 12, 24), Email = "isabella.fernandes@email.com" },
                new Aluno { Codigo = "A00035", Nome = "Pedro Gomes", DataNascimento = new DateTime(1961, 10, 3), Email = "pedro.gomes@email.com" },
                new Aluno { Codigo = "A00036", Nome = "Beatriz Silva", DataNascimento = new DateTime(1965, 10, 22), Email = "beatriz.silva@email.com" },
                new Aluno { Codigo = "A00037", Nome = "Manuela Ribeiro", DataNascimento = new DateTime(1964, 11, 2), Email = "manuela.ribeiro@email.com" },
                new Aluno { Codigo = "A00038", Nome = "Beatriz Jesus", DataNascimento = new DateTime(1951, 12, 18), Email = "beatriz.jesus@email.com" },
                new Aluno { Codigo = "A00039", Nome = "Pedro Santos", DataNascimento = new DateTime(1982, 8, 1), Email = "pedro.santos@email.com" },
                new Aluno { Codigo = "A00040", Nome = "Julia Souza", DataNascimento = new DateTime(1988, 8, 9), Email = "julia.souza@email.com" },
                new Aluno { Codigo = "A00041", Nome = "Carlos Lima", DataNascimento = new DateTime(2007, 8, 14), Email = "carlos.lima@gmail.com.br" },
                new Aluno { Codigo = "A00042", Nome = "Sofia Ribeiro", DataNascimento = new DateTime(1995, 8, 29), Email = "sofia.ribeiro@email.com" },
                new Aluno { Codigo = "A00043", Nome = "Carlos Carvalho", DataNascimento = new DateTime(1997, 8, 31), Email = "carlos.carvalho@email.com" },
                new Aluno { Codigo = "A00044", Nome = "João Carvalho", DataNascimento = new DateTime(1988, 4, 9), Email = "joão.carvalho@email.com" },
                new Aluno { Codigo = "A00045", Nome = "João Souza", DataNascimento = new DateTime(1955, 5, 20), Email = "joão.souza@email.com" },
                new Aluno { Codigo = "A00046", Nome = "João Santos", DataNascimento = new DateTime(1985, 10, 13), Email = "joão.santos@email.com" },
                new Aluno { Codigo = "A00047", Nome = "Pedro Jesus", DataNascimento = new DateTime(1987, 7, 15), Email = "pedro.jesus@email.com" },
                new Aluno { Codigo = "A00048", Nome = "Ana Alves", DataNascimento = new DateTime(1988, 6, 24), Email = "ana.alves@gmail.com" },
                new Aluno { Codigo = "A00049", Nome = "Alice Gomes", DataNascimento = new DateTime(1973, 1, 11), Email = "alice.gomes@email.com" },
                new Aluno { Codigo = "A00050", Nome = "Beatriz Martins", DataNascimento = new DateTime(2004, 8, 31), Email = "beatriz.martins@email.com" },
                new Aluno { Codigo = "A00051", Nome = "Pedro Barbosa", DataNascimento = new DateTime(1969, 5, 9), Email = "pedro.barbosa@email.com" },
                new Aluno { Codigo = "A00052", Nome = "Alice Carvalho", DataNascimento = new DateTime(1982, 12, 12), Email = "alice.carvalho@email.com" },
                new Aluno { Codigo = "A00053", Nome = "Ana Costa", DataNascimento = new DateTime(2009, 3, 25), Email = "ana.costa@gmail.com" },
                new Aluno { Codigo = "A00054", Nome = "Manuela Mendes", DataNascimento = new DateTime(1967, 2, 23), Email = "manuela.mendes@email.com" },
                new Aluno { Codigo = "A00055", Nome = "Ana Monteiro", DataNascimento = new DateTime(1961, 7, 17), Email = "ana.monteiro@email.com" },
                new Aluno { Codigo = "A00056", Nome = "Isabella Silva", DataNascimento = new DateTime(1953, 1, 3), Email = "isabella.silva@email.com" },
                new Aluno { Codigo = "A00057", Nome = "Felipe Pereira", DataNascimento = new DateTime(2007, 10, 9), Email = "felipe.pereira@email.com" },
                new Aluno { Codigo = "A00058", Nome = "Isabella Silva", DataNascimento = new DateTime(1966, 3, 22), Email = "isabella.silva@email.com" },
                new Aluno { Codigo = "A00059", Nome = "Beatriz Martins", DataNascimento = new DateTime(1991, 1, 19), Email = "beatriz.martins@email.com" },
                new Aluno { Codigo = "A00060", Nome = "Gabriel Gomes", DataNascimento = new DateTime(1958, 3, 16), Email = "gabriel.gomes@gmail.com@" },
                new Aluno { Codigo = "A00061", Nome = "Beatriz Silva", DataNascimento = new DateTime(1994, 10, 25), Email = "beatriz.silva@email.com" },
                new Aluno { Codigo = "A00062", Nome = "Ana Gomes", DataNascimento = new DateTime(1997, 10, 27), Email = "ana.gomes@gmail.com" },
                new Aluno { Codigo = "A00063", Nome = "Felipe Almeida", DataNascimento = new DateTime(1979, 11, 20), Email = "felipe.almeida@email.com" },
                new Aluno { Codigo = "A00064", Nome = "João Rodrigues", DataNascimento = new DateTime(1962, 12, 14), Email = "joão.rodrigues@email.com" },
                new Aluno { Codigo = "A00065", Nome = "Gustavo Lima", DataNascimento = new DateTime(1952, 6, 7), Email = "gustavo.lima@email.com" },
                new Aluno { Codigo = "A00066", Nome = "Manuela Costa", DataNascimento = new DateTime(1956, 12, 31), Email = "manuela.costa@email.com" },
                new Aluno { Codigo = "A00067", Nome = "Alice Monteiro", DataNascimento = new DateTime(1998, 7, 16), Email = "alice.monteiro@email.com" },
                new Aluno { Codigo = "A00068", Nome = "Felipe Souza", DataNascimento = new DateTime(1957, 12, 4), Email = "felipe.souza@email.com" },
                new Aluno { Codigo = "A00069", Nome = "Felipe Costa", DataNascimento = new DateTime(1977, 5, 30), Email = "felipe.costa@email.com" },
                new Aluno { Codigo = "A00070", Nome = "João Ribeiro", DataNascimento = new DateTime(1999, 6, 17), Email = "joão.ribeiro@email.com" },
                new Aluno { Codigo = "A00071", Nome = "Sofia Souza", DataNascimento = new DateTime(1960, 10, 21), Email = "sofia.souza@email.com" },
                new Aluno { Codigo = "A00072", Nome = "Diego Mendes", DataNascimento = new DateTime(1966, 8, 29), Email = "diego.mendes@email.com" },
                new Aluno { Codigo = "A00073", Nome = "Diego Fernandes", DataNascimento = new DateTime(2001, 10, 3), Email = "diego.fernandes@email.com" },
                new Aluno { Codigo = "A00074", Nome = "Gustavo Araujo", DataNascimento = new DateTime(2006, 5, 30), Email = "gustavo.araujo@email.com" },
                new Aluno { Codigo = "A00075", Nome = "Beatriz Oliveira", DataNascimento = new DateTime(1962, 11, 21), Email = "beatriz.oliveira@email.com" },
                new Aluno { Codigo = "A00076", Nome = "Beatriz Costa", DataNascimento = new DateTime(1989, 7, 6), Email = "beatriz.costa@email.com" },
                new Aluno { Codigo = "A00077", Nome = "Joana Souza", DataNascimento = new DateTime(1991, 5, 22), Email = "joana.souza@gmail.com" },
                new Aluno { Codigo = "A00078", Nome = "Isabella Araujo", DataNascimento = new DateTime(1950, 11, 18), Email = "isabella.araujo@email.com" },
                new Aluno { Codigo = "A00079", Nome = "Felipe Pereira", DataNascimento = new DateTime(1981, 1, 5), Email = "felipe.pereira@email.com" },
                new Aluno { Codigo = "A00080", Nome = "Sofia Jesus", DataNascimento = new DateTime(1988, 4, 4), Email = "sofia.jesus@email.com" },
                new Aluno { Codigo = "A00081", Nome = "Sofia Alves", DataNascimento = new DateTime(1977, 6, 29), Email = "sofia.alves@email.com" },
                new Aluno { Codigo = "A00082", Nome = "Ana Pereira", DataNascimento = new DateTime(1968, 2, 3), Email = "ana.pereira@email.com" },
                new Aluno { Codigo = "A00083", Nome = "Julia Martins", DataNascimento = new DateTime(1996, 6, 26), Email = "julia.martins@email.com" },
                new Aluno { Codigo = "A00084", Nome = "Gabriel Barbosa", DataNascimento = new DateTime(1979, 2, 21), Email = "gabriel.barbosa@email.com" },
                new Aluno { Codigo = "A00085", Nome = "Pedro Araujo", DataNascimento = new DateTime(1953, 10, 8), Email = "pedro.araujo@email.com" },
                new Aluno { Codigo = "A00086", Nome = "Lucas Gomes", DataNascimento = new DateTime(1958, 9, 14), Email = "lucas.gomes@email.com" },
                new Aluno { Codigo = "A00087", Nome = "Carlos Carvalho", DataNascimento = new DateTime(1973, 5, 28), Email = "carlos.carvalho@email.com" },
                new Aluno { Codigo = "A00088", Nome = "Ana Mendes", DataNascimento = new DateTime(1963, 5, 17), Email = "ana.mendes@gmail.com" },
                new Aluno { Codigo = "A00089", Nome = "Ana Souza", DataNascimento = new DateTime(2004, 10, 28), Email = "ana.souza@gmail.com" },
                new Aluno { Codigo = "A00090", Nome = "Isabella Jesus", DataNascimento = new DateTime(1954, 3, 20), Email = "isabella.jesus@email.com" },
                new Aluno { Codigo = "A00091", Nome = "Laura Alves", DataNascimento = new DateTime(1980, 7, 1), Email = "laura.alves@email.com" },
                new Aluno { Codigo = "A00092", Nome = "Beatriz Ribeiro", DataNascimento = new DateTime(1989, 3, 17), Email = "beatriz.ribeiro@email.com" },
                new Aluno { Codigo = "A00093", Nome = "Gabriel Santos", DataNascimento = new DateTime(1985, 8, 28), Email = "gabriel.santos@email.com" },
                new Aluno { Codigo = "A00094", Nome = "Pedro Monteiro", DataNascimento = new DateTime(1974, 7, 21), Email = "pedro.monteiro@email.com" },
                new Aluno { Codigo = "A00095", Nome = "Beatriz Carvalho", DataNascimento = new DateTime(1954, 8, 17), Email = "beatriz.carvalho@email.com" },
                new Aluno { Codigo = "A00096", Nome = "Julia Ribeiro", DataNascimento = new DateTime(1966, 11, 25), Email = "julia.ribeiro@email.com" },
                new Aluno { Codigo = "A00097", Nome = "Maria Almeida", DataNascimento = new DateTime(2004, 2, 29), Email = "maria.almeida@email.com" },
                new Aluno { Codigo = "A00098", Nome = "Miguel Santos", DataNascimento = new DateTime(1999, 5, 10), Email = "miguel.santos@email.com" },
                new Aluno { Codigo = "A00099", Nome = "Isabella Rodrigues", DataNascimento = new DateTime(2009, 11, 30), Email = "isabella.rodrigues@email.com" },
                new Aluno { Codigo = "A00100", Nome = "Pedro Ribeiro", DataNascimento = new DateTime(1965, 11, 24), Email = "pedro.ribeiro@email.com" },
            };

        }
    }
}
